services:
  accounts:
    image: "sakshisingh1094/accounts:s2"
    container_name: accouts_ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank

networks:
  eazybank:
    driver: "bridge"
